[versions]
agp = "8.7.2"
compileSdk = "35"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
# for test elf loader
tencent-mmkv = { module = "com.tencent:mmkv-static", version = "1.3.11" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
